name: Trigger auto deployment for continuous-deployment-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/continuous-deployment-test-AutoDeployTrigger-b912ca07-6746-46a6-b790-f94ff3b5dbc1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: continuoustestregistry.azurecr.io
          registryUsername: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_REGISTRY_PASSWORD }}
          containerAppName: continuous-deployment-test
          resourceGroup: ContinuousTests
          imageToBuild: continuoustestregistry.azurecr.io/continuous-deployment-test:${{ github.sha }}
          dockerfilePath: Dockerfile


